import Head from 'next/head'
import Link from 'next/dist/client/link'
import Image from "next/image"
import { arrowUp, emailLogo2, icon1, locationIcon, phoneSVG } from '../components/icons'
import img4 from '../public/media/img4.jpg'
import img5 from '../public/media/img5.jpg'
import newImg2 from "../public/media/newImg2.jpg"
import softlogo2 from "../public/media/softlogo2.jpg"
import aboutImage1 from "../public/media/aboutImage1.jpg"


import { Header } from '../components/header'
import { Footer } from '../components/footer'
import { useRef } from "react";

export default function Home() {
  function toTop() {
    window.scrollTo({
      top: 0,
      behavior: "smooth"
    })
  }

  const introRef = useRef();
  const aboutRef = useRef();
  const featuresRef = useRef();
  const contactsRef = useRef();

  const onRefClick = (ref)=>{
    ref.current.scrollIntoView({ behavior: "smooth"})
  }

  return (
    <div id='IndexUz'>
      <Head>
        <title>Soft Dental Clinic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='flex flex-col w-full min-h-screen text-textGray'>
        <main className='flex-auto bg-mainGray'>
          <section id='intro' ref={introRef}  className='min-h-screen w-full flex flex-col relative'>
            <div className='fixed top-0 inset-x-0 bg-mainGray z-40'><Header onRefClick={onRefClick} introRef={introRef} aboutRef={aboutRef} featuresRef={featuresRef} contactsRef={contactsRef}/></div>
            <div className='flex-auto flex items-center justify-center'>
              <div className='max-w-[1200px] mx-auto w-full px-6 grid md:grid-cols-2 items-center gap-[48px] pb-[40px] pt-[90px]'>
                <div className='w-full flex flex-col space-y-[16px] md:space-y-[24px] items-center md:items-start'>
                  <p className='title teal'>Asosiy</p>
                  <p className='uppercase font-bold text-[22px] leading-[30px] md:text-[32px] md:leading-[38px] lg:text-[44px] lg:leading-[48px] text-center md:text-left'>Yuqori sifatli va og&apos;riqsiz - <span className='text-mainBlue'>stomatologiya</span></p>
                  <p className='opacity-60 text-center md:text-left'>Biz xizmatlarning to&apos;liq spektrini va har qanday muammolarni hal qilish uchun kompleks yondashuvni taklif qilamiz va bu barcha oila a&apos;zolari uchun sog&apos;lom tishlar va og&apos;iz boshlig&apos;ining kafolatidir.</p>
                  <button onClick={()=> onRefClick(contactsRef)} className='buttonBlue'>Qabulga yozilish</button>
                </div>
                <div className='w-full h-full gridjon gap-[24px]'>
                  <div className='w-full gridMin gap-[24px]'>
                    <div className='h-full gridTop gap-[24px]'>
                      <div className='w-full hidden lg:flex flex-col justify-end space-y-4 items-end'>
                        <div className='border a5 flex self-end w-[60px] h-[60px] md:w-[90px] md:h-[90px] lg:w-[60px] lg:h-[60px]'></div>
                        <div className='border a4 bg-mainBlue h-[80px] md:h-[100px] lg:h-[80px] w-[90%]'></div>
                      </div>
                      <div className='w-full a3 h-[200px] sm:h-[240px] md:h-[180px] lg:h-[200px] self-end relative'>
                        <Image src={img5} alt="image" layout='fill' objectFit='cover' />
                      </div>
                    </div>
                    <div className='a2 h-[200px] sm:h-[240px] md:h-[180px] lg:h-[160px] relative'>
                      <Image alt='image' src={img4} layout='fill' objectFit='cover' />
                    </div>
                  </div>
                  <div className='w-full a1 relative'>
                    <Image alt='image' src={newImg2} layout='fill' objectFit='cover' />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section id='about' ref={aboutRef}>
            <div className='bg-white flex justify-center items-center py-[40px] md:pb-[80px] lg:pb-[100px]'>
              <div className='max-w-[1200px] mx-auto px-4 w-full h-full flex md:grid md:grid-cols-2 items-center gap-[48px]'>
                <div className='aboutGrid h-full'>
                  <div className='aboutGrid__Top self-end'>
                    <div className='w-full md:h-[180px] lg:h-[220px] topDiv relative'>
                      <Image src={softlogo2} alt="image" layout='fill' objectFit='cover' />
                    </div>
                    <div className='w-[120px] h-[120px] bg-teal rounded-full'></div>
                  </div>
                  <div>
                    <div className='md:h-[240px] lg:h-[300px] bottomDiv relative w-full'>
                      <Image src={aboutImage1} alt="image" layout='fill' objectFit='cover' />
                    </div>
                  </div>
                </div>
                <div className='flex flex-col items-center md:items-start justify-center space-y-[16px] md:space-y-[24px]'>
                  <p className='teal title'>Biz haqimizda</p>
                  <p className='uppercase font-bold text-[22px] leading-[30px] md:text-[32px] md:leading-[38px] lg:text-[44px] lg:leading-[48px] text-center md:text-left'>BEMOR SALOMATLIGI BIZNING ENG YUKOR QIMMATIMIZDIR</p>
                  <p className='opacity-60 text-center md:text-left'>Eng yangi asbob-uskunalar, yuqori aniqlikdagi texnologiyalar va jahon tibbiyotining eng yaxshi yutuqlari bemorlarga mutlaqo yangi, misli ko&apos;rilmagan og&apos;riqsiz davolanish imkonini beradi.</p>
                  <div>
                    <button className='buttonBlue'>Batafsil ma&apos;lumot</button>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section id='features' ref={featuresRef}>
            <div className='min-h-screen 2xl:h-auto max-w-[1200px] mx-auto px-4 py-[40px] md:py-[60px] flex flex-col items-center justify-center space-y-[30px] md:space-y-[60px]'>  {/* pt-[80px] */}
              <div className='flex flex-col justify-center items-center space-y-[10px] md:space-y-[30px]'>
                <p className='teal title'>Xizmatlar</p>
                <p className='subtitle'>Barcha xizmatlar</p>
              </div>
              <div className='grid sm:grid-cols-2 md:grid-cols-3 gap-4 2xl:gap-10'>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Implantatsiya</p>
                    <p className='featureContent'>Implant - bu protezlash uchun intramaxillarar suyak to&apos;qimalariga kiritish uchun mo&apos;ljallangan sun&apos;iy ravishda yaratilgan tuzilma. Implantatsiyaning afzalligi shundaki, klassik protezlardan farqli o&apos;laroq, sog&apos;lom qo&apos;shni tishlarni tayyorlash kerak emas. Odatda implantlar juda uzoq vaqt davomida joylashtiriladi.</p>
                  </div>
                </div>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Shponlar</p>
                    <p className='featureContent'>O&apos;zingizga Gollivud tabassumini bering! Bizning mijozlarimizga stomatologiya sohasidagi olimlarning so&apos;nggi yutuqlari taklif etiladi. Masalan, tishlarni shpon bilan badiiy tiklash. Onlaylar tishlarning old qismida joylashgan bo&apos;lib, ularni qor-oq rangga aylantiradi. Shifokorlar, bioestetik bilimlari tufayli tishlarga kerakli shaklni beradilar. Veneerlar juda ko&apos;p afzalliklarga ega va keramika, chinni yoki kompozit materiallardan - tanlov faqat moliyaga tegishli.</p>
                  </div>
                </div>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Tishlarni oqartirish</p>
                    <p className='featureContent'>Tishlarni oqartirish - tishlarning soyasini o&apos;zgartirish uchun mashhur stomatologik protsedura. Barcha ma&apos;lum usullar kimyoviy bo&apos;linadi, bunda tish emaliga ta&apos;sir oqartiruvchi preparatlar bilan amalga oshiriladi va mexanik emalning tabiiy rangiga tozalovchi kompozitsiyani va unga siqilgan havo etkazib berish orqali erishiladi. Oqartirish usuli Vitam Dental Clinic stomatologi tomonidan har bir kishi uchun alohida tanlanadi.</p>
                  </div>
                </div>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Jarrohlik stomatologiyasi</p>
                    <p className='featureContent'>Ko&apos;pchilik stomatologning asosiy vazifasi tishlarni olib tashlash deb o&apos;ylaydi. Lekin bu xato. Uning maqsadi, birinchi navbatda, hatto eng muammoli tishlarning butunligini tiklash va maksimal darajada saqlashdir. U protezlash, yallig&apos;lanishlarni davolash (sinusit, xo&apos;ppoz, osteomielit, periostit, periodontit), sinusni ko&apos;tarish, tilning frenulumini kesish va boshqalarni amalga oshiradi. Soft Dental stomatologiya klinikasida jarrohlik muolajalari faqat topikal behushlik usullaridan foydalangan holda amalga oshiriladi.</p>
                  </div>
                </div>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Ortodontiya</p>
                    <p className='featureContent'>Zamonaviy ortodontiya chiroyli tabassum yaratish uchun keng ko&apos;lamli vositalarni taklif qiladi va ortodontist ushbu vositalardan qaysi biri muayyan bemorga davolanishdan keyin eng yaxshi natijaga erishishga yordam berishini aniqlaydi.</p>
                  </div>
                </div>
                <div className='w-full featureCard flex flex-col space-y-4'>
                  <div className='w-16 h-16 rounded-full bg-mainGray teal flex items-center justify-center'>{icon1}</div>
                  <div className='flex flex-col space-y-4'>
                    <p className='featureTitle'>Kariyesni davolash.</p>
                    <p className='featureContent'>Terapevtik stomatologiya stomatologiyada eng keng tarqalgan xizmatdir. Sifatli davolangan tishlar bemorlar salomatligining kaliti, to&apos;liq huquqli ortodontik, ortopedik, periodontal davolash va implantatsiya uchun asosdir.</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section id='contacts' ref={contactsRef}>
            <div className='md:h-screen flex flex-col space-y-8 md:space-y-0 md:flex-row justify-center items-center relative overflow-hidden'>
              <div className='relative w-full h-[280px] sm:h-[380px] md:h-full z-20'>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1915.8187624379536!2d69.19298099587215!3d41.296424173092824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8bd638477053%3A0x257a279a0e8f4348!2zNzVXVitXRmdsINCi0L7RiNC60LXQvdGCIDEwMDE3MywgT2B6YmVraXN0b24!5e0!3m2!1suz!2s!4v1652272449475!5m2!1suz!2s" className='absolute top-0 left-0 w-full h-full z-20' allowFullScreen="" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>
              </div>
              <div className='md:absolute md:top-0 md:left-0 w-full md:h-full text-white'>
                <div className='max-w-[1200px] mx-auto px-4 h-full flex items-center z-10'>
                  <div className='bg-mainBlue md:w-[500px] w-full flex flex-col space-y-4 sm:space-y-8 p-4 sm:p-8 md:p-10 rounded-[15px] z-30'>
                    <p className='mapContentTitle'>Kontaktlar</p>
                    <div className='flex flex-col space-y-4 sm:space-y-8'>
                      <div className='flex items-center space-x-4' id='location'>
                        <div className='w-8'>
                          <div className='bg-lightBlue w-8 h-8 rounded-full flex justify-center items-center'>{locationIcon}</div>
                        </div>
                        <div className='flex-auto'>
                          <Link href="/">
                            <a className="contactsInfo">Uchtepa tumani, 14-mavze 14-uy 27/37</a>
                          </Link>
                        </div>
                      </div>
                      <div className='flex items-center space-x-4' id='phone_number'>
                        <div className='w-8'>
                          <div className='bg-lightBlue w-8 h-8 rounded-full flex justify-center items-center'>{phoneSVG}</div>
                        </div>
                        <div className='flex-auto'>
                          <Link href="tel:+998997950059">
                            <a className="contactsInfo googleFont">+998 99 795 00 59</a>
                          </Link>
                        </div>
                      </div>
                      <div className='flex items-center space-x-4' id='email'>
                        <div className='w-8'>
                          <div className='bg-lightBlue w-8 h-8 rounded-full flex justify-center items-center'>{emailLogo2}</div>
                        </div>
                        <div className='flex-auto'>
                          <Link href="mailto:bobir.nazarov00@gmail.com">
                            <a className="contactsInfo">bobir.nazarov00@gmail.com</a>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>
        <Footer />
        <div id='toTop' onClick={toTop} className='bg-white h-8 w-8 fixed bottom-10 md:bottom-6 right-6 cursor-pointer flex items-center justify-center z-30 hover:bg-opacity-40 transition duration-100 rounded border border-white'>{arrowUp}</div>
      </div>
    </div>
  )
}
