import Head from 'next/head'
import Link from 'next/dist/client/link'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import { arrowUp } from '../components/icons'

export default function Home() {
  function toTop() {
    window.scrollTo({
      top: 0,
      behavior: "smooth"
    })
  }

  return (
    <div>
      <Head>
        <title>Dentist | Bosh sahifa</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div id='IndexUz' className='flex flex-col w-full min-h-screen bg-ghost text-black'>
        <section id='intro' className='h-screen z-20 w-full flex flex-col bg-gradient-to-b from-lightBlue to-mainBlue relative'>
          <div className='fixed top-0 inset-x-0 z-20'><Header /></div>
          <div className='flex-auto text-white flex  items-center justify-center'>
            <div className='max-w-[1200px] mx-auto px-6 py-4'>Section 1</div>
          </div>
        </section>
        <main className='flex-auto'>
          <section id='about'>
            <div className='max-w-[1200px] mx-auto px-6 py-4'>Section 2</div>    
          </section>
          <section id='features' className="bg-mainBlue text-white">
            <div className='max-w-[1200px] mx-auto px-6 py-10'>
              <div className='grid sm:grid-cols-2 lg:grid-cols-3 gap-6'>
                <div className='featuresCard w-full h-48 bg-white rounded'></div>
                <div className='featuresCard w-full h-48 bg-white rounded'></div>
                <div className='featuresCard w-full h-48 bg-white rounded'></div>
                <div className='featuresCard w-full h-48 bg-white rounded'></div>
              </div>
            </div>
          </section>
          <section id='blog'>
            <div className='max-w-[1200px] mx-auto px-6 py-10 flex flex-col space-y-6'>
              <div className='grid sm:grid-cols-2 lg:grid-cols-3 gap-6'>
                <div className='blogCard w-full h-48 bg-white rounded'></div>
                <div className='blogCard w-full h-48 bg-white rounded'></div>
                <div className='blogCard w-full h-48 bg-white rounded'></div>
                <div className='blogCard w-full h-48 bg-white rounded'></div>
              </div>
              <div className='flex items-center justify-center'>
                <Link href="/blog">
                  <a className='border border-black'>Batafsil</a>
                </Link>
              </div>
            </div>    
          </section>
        </main>
        <Footer />
        <div id='toTop' onClick={toTop} className='bg-white h-8 w-8 fixed bottom-10 right-6 cursor-pointer md:flex items-center justify-center z-20 hidden hover:bg-opacity-80 transition duration-100 rounded border border-white'>{arrowUp}</div>
      </div>
    </div>
  )
}
